package AdditionApp;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 8, 2015 11:52:41 AM IST
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  String otherClientStatus ();
  void shutdown ();
} // interface AdditionOperations
